# Generated by Django 5.0.4 on 2024-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='dateOfSubmission',
        ),
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(default='Orange and Beige Simple Book Store Logo.png', upload_to=''),
        ),
    ]
