# Generated by Django 5.0.4 on 2024-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_photos_dateofsubmission_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
